version: '2'
services:
  static:
    build:
      context: ./devops/static-${SERVER_TYPE}
    ports:
      - 80:80
      - 443:443
    links:
      - server
  server:
    build:
      context: ./devops/server
    links:
      - postgres
      - redis
      - scylla
  postgres:
    build:
      context: ./devops/postgres
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
  redis:
    build:
      context: ./devops/redis
  scylla:
    build:
      context: ./devops/scylla
  mail:
    build:
      context: ./devops/mail
    environment:
      - maildomain=${EMAIL_SERVER_DOMAIN}
      - smtp_user=${EMAIL_SERVER_USER}:${EMAIL_SERVER_PASSWORD}
