version: '2'
services:
  static:
    build:
      context: ./devops/static
    ports:
      - 80:80
    links:
      - server
  server:
    build:
      context: ./devops/server
    links:
      - postgres
      - redis
      - scylla
    ports:
      - 7777:7777
  postgres:
    build:
      context: ./devops/postgres
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
  redis:
    build:
      context: ./devops/redis
  scylla:
    build:
      context: ./devops/scylla