version: '2'
services:
  static:
    build:
      context: ./devops/static
    ports:
      - 80:80
    links:
      - server
  server:
    build:
      context: ./devops/server
    links:
      - postgres
      - redis
    ports:
      - 7777:7777
  postgres:
    build:
      context: ./devops/postgres
    environment:
      - POSTGRES_PASSWORD
  redis:
    build:
      context: ./devops/redis
